CREATE TABLE "reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"report_type" varchar(50) NOT NULL,
	"protocolo" varchar(100),
	"protocolo_custom" varchar(100),
	"title" text NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"user_id" text,
	"user_name" text,
	"metadata" jsonb,
	"kit_actividades" jsonb,
	"manuales_guias" jsonb,
	"hub_participantes" text,
	"metricas_sesiones" jsonb,
	"ranking_sesiones" jsonb,
	"distribucion_region" jsonb,
	"analisis_geografico" jsonb,
	"descripcion_general" jsonb,
	"reporte_analisis_tecnico" text,
	"categorias_proyectos" jsonb,
	"actividades_principales" jsonb,
	"mentorias" jsonb,
	"obstaculos_comunes" jsonb,
	"patrocinadores" jsonb,
	"recomendaciones_estrategicas" jsonb,
	"desafios_aprendizajes" jsonb,
	"testimonios" jsonb,
	"datos_participantes" jsonb,
	"habilidades_clave" jsonb,
	"experiencia_previa_blockchain" jsonb,
	"tecnologias_ocupadas" jsonb,
	"aspectos_valorados" jsonb,
	"impacto_percibido" jsonb,
	"conclusiones_aprendizajes" jsonb,
	"status" varchar(20) DEFAULT 'draft',
	"attachments" jsonb,
	"is_ai_generated" varchar(10) DEFAULT 'false',
	"ai_model" text,
	"ai_prompt" text
);
